query searchRepos($searchTerm: String!, $first: Int!) {
  search(query: $searchTerm, first: $first, type: REPOSITORY) {
    edges {
      node {
        ... on Repository {
          name,
          url,
          owner {
            login
          }
        }
      }
    }
  }
}
