name: Build GitHub Omnibox

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - uses: actions/checkout@v2
      - name: NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache NPM Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Build Extension
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: npm run build:prod
      - name: Store build result
        uses: actions/upload-artifact@v2
        with:
          name: github-omnibox-${{ steps.extract_version.outputs.version }}
          path: dist
